cxxflags = 'CXXFLAGS=\$CXXFLAGS -msse3 -fPIC';
%mex('knn_mex.cpp', cxxflags, 'libANN.a');
mex -I. -IANN/ knn_mex.cpp src/ANN.cpp   ...
            src/kd_pr_search.cpp src/kd_split.cpp src/kd_util.cpp  ...
            src/kd_fix_rad_search.cpp src/kd_search.cpp src/kd_tree.cpp ...
            src/kd_dump.cpp src/bd_pr_search.cpp src/bd_tree.cpp src/perf.cpp ... 
            src/bd_fix_rad_search.cpp src/bd_search.cpp src/brute.cpp;
disp('done!');